---
name: build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libmpv-dev libglib2.0-dev libavformat-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mpris.so
          path: mpris.so
          if-no-files-found: error

      - name: Prepare for test
        run: |
          sudo apt install mpv playerctl sound-theme-freedesktop bash dbus xvfb xauth jq socat gawk

      - name: Run tests
        run: |
          make test

      - name: Check git files unmodified
        run: |
          git diff --exit-code HEAD

      - name: Check .gitignore matches generated files
        run: |
          ! git ls-files --others --exclude-standard | grep .
      
      - name: Publish to GitHub Packages
        run: |
         curl -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
         -H "Content-Type: application/octet-stream" \
         --data-binary "@dist/my-binary-${{ github.ref_name }}.tar.gz" \
         "https://uploads.github.com/repos/${{ github.repository }}/releases/assets?name=mpv-mpris-${{ github.ref_name }}.tar.gz"


---
